import * as moment from 'moment';
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import * as redux from 'redux';
import * as ReactRouter from 'react-router';
import * as ReactBootstrap from 'react-bootstrap';
import * as ReactBootstrapTable from 'react-bootstrap-table';
import * as ReactDraftWYSIWYG from 'react-draft-wysiwyg';
import * as DraftJS from 'draft-js';
import * as DraftJSToHTML from 'draftjs-to-html';
import * as ReactDND from 'react-dnd';
import * as ReactDNDHTML5Backend from 'react-dnd-html5-backend';
import * as Reactstrap from 'reactstrap';
import * as ReactAddonsCssTransitionGroup from 'react-addons-css-transition-group';
import * as ReactAddonsTransitionGroup from 'react-addons-transition-group';
import * as ReactSelect from 'react-select';
import * as DatePicker from 'react-datepicker';
import * as ReactSortableHoc from 'react-sortable-hoc';
import * as Lightbox  from 'react-image-lightbox';

window['react-bootstrap-table'] = ReactBootstrapTable;
window['react-bootstrap'] = ReactBootstrap;
window['react-router'] = ReactRouter;
window['react-dom'] = ReactDOM;
window['redux'] = redux;
window['react'] = React;
window['moment'] = moment;
window['react-draft-wysiwyg'] = ReactDraftWYSIWYG;
window['draft-js'] = DraftJS;
window['draftjs-to-html'] = DraftJSToHTML;
window['react-dnd'] = ReactDND;
window['react-dnd-html5-backend'] = ReactDNDHTML5Backend;
window['reactstrap'] = Reactstrap;
window['react-addons-css-transition-group'] = ReactAddonsCssTransitionGroup;
window['react-addons-transition-group'] = ReactAddonsTransitionGroup;
window['react-select'] = ReactSelect;
window['react-datepicker'] = DatePicker;
window['react-sortable-hoc'] = ReactSortableHoc;
window['react-image-lightbox'] = Lightbox;
